name: Bug Report
description: File a bug report to help us improve ensureJson
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package is affected?
      options:
        - ensure-json (Python)
        - ensure-json (JavaScript/TypeScript)
        - Both
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the bug.
      placeholder: |
        1. Install package with '...'
        2. Run code '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, I got...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Please provide a minimal code example that demonstrates the issue.
      render: python
      placeholder: |
        from ensure_json import ensure_json
        # Your code here
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your environment.
      placeholder: |
        - OS: [e.g., Ubuntu 22.04, macOS 14.0, Windows 11]
        - Python version: [e.g., 3.11.5] OR Node.js version: [e.g., 20.5.0]
        - Package version: [e.g., 0.1.1]
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (stack traces, error messages, screenshots, etc.).
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting.
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided a minimal reproducible example
          required: false
        - label: I am using the latest version of the package
          required: false
